# Feature Finding Example

In [ ]:
# Load default settings and set custom raw_path
from alphapept.settings import settings

settings['raw']['raw_path'] = 'F:/rawdata/04_hela_testrun/20190402_QX1_SeVW_MA_HeLa_500ng_LC11.raw'


# Convert to npz

from alphapept.io import raw_to_npz

out_path = raw_to_npz(settings["raw"])
settings["raw"]["query_path"] = out_path[0]
print('Raw file(s) saved to {}'.format(out_path))

Raw File saved to F:/rawdata/04_hela_testrun/20190402_QX1_SeVW_MA_HeLa_500ng_LC11.npz
Raw file(s) saved to ['F:/rawdata/04_hela_testrun/20190402_QX1_SeVW_MA_HeLa_500ng_LC11.npz']

In [ ]:
from alphapept.feature_finding import find_features
import numpy as np

query_data = np.load(settings["raw"]["query_path"], allow_pickle=True)

df = find_features(query_data)

Loaded 13,230 centroids.

C:\ProgramData\Anaconda3\envs\alphap\lib\site-packages\numba\ir_utils.py:2041: NumbaPendingDeprecationWarning:
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'centroids' of function 'connect_centroids_forward'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "alphapept\feature_finding.py", line 189:
@njit
def connect_centroids_forward(centroids, max_centroids, max_gap, ppm_tol):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
C:\ProgramData\Anaconda3\envs\alphap\lib\site-packages\numba\ir_utils.py:2041: NumbaPendingDeprecationWarning:
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'centroids' of function 'connect_centroids_backward'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "alphapept\feature_finding.py", line 232:
@njit
def connect_centroids_backward(centroids, max_centroids, max_gap, ppm_tol):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))

A total of 992,051 hills extracted. Average hill length 16.04
Split 992,051 hills into 1,239,960 hills
Filtered 1,239,960 hills. Remaining 1,221,467 hills

C:\ProgramData\Anaconda3\envs\alphap\lib\site-packages\numba\ir_utils.py:2041: NumbaPendingDeprecationWarning:
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'hill_data' of function 'get_hill_data_numba'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "alphapept\feature_finding.py", line 581:
@njit
def get_hill_data_numba(hill_data):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))

Extracting hill stats complete
Found 200034 pre isotope patterns.
Extracted 218781 isotope patterns.
Report complete.
Time elapsed 777.3481254577637

In [ ]:
df

,mz,mz_std,most_abundant_mz,charge,rt_start,rt_apex,rt_end,fhwm,n_isotopes,n_scans,mass,int_apex,int_sum
0,300.252808,0.000066,300.253052,1,114.16629,114.19925,114.28740,0.01809,4,34,299.245531,18736336,181103378
1,313.273254,0.000064,313.273438,1,114.16993,114.20290,114.21387,0.01809,4,13,312.265978,12335569,109910648
2,314.220978,0.000065,314.223633,1,114.55037,114.57930,114.67485,0.09503,3,33,313.213701,2549398,72929837
3,319.226379,0.000016,319.226440,1,114.31601,114.39871,114.46070,0.05837,3,30,318.219103,3318992,63216527
4,316.236664,0.000014,316.237061,1,114.44981,114.50227,114.50953,0.00363,2,17,315.229387,1214422,22613664
...,...,...,...,...,...,...,...,...,...,...,...,...,...
218776,322.688599,0.000116,322.690094,2,119.97170,119.98536,119.99815,0.02645,2,7,643.362644,213025,1604461
218777,338.199799,0.000003,339.197449,1,119.97170,119.97170,119.99815,0.02190,2,7,337.192522,244905,1691240
218778,390.201447,0.000287,390.203888,3,119.97170,119.98536,119.99815,0.02190,2,6,1167.582510,186037,1224084
218779,384.689056,0.000128,384.689301,1,119.97170,119.99360,119.99360,0.01366,2,6,383.681780,227461,1271007
218780,416.223694,0.000108,417.229126,1,119.98536,119.99360,119.99815,0.00000,2,4,415.216417,130494,656450